### PR TITLE
Replace HTTP with HTTPS, because HTTP breaks HTTPS.

### PR DESCRIPTION
**Pull request by yackermann**

### CODE REVIEW

**Comment by iamtrask** [comment]
thank you!

**Comment by yackermann** [comment]
@iamtrask *) Thank you for your posts. THEY ARE AWESOME *)

**Comment by iamtrask** [comment]
You are absolutely welcome! I'm so glad you like them. :)

**Comment by iamtrask** [comment]
Also, I want to visit New Zealand someday. You live in an awesome country.

**Pull request merged**
